
name: Build sysroot images
on: [push, workflow_dispatch]
jobs:
  sysroot:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        # os: [fedora~37, ubuntu~kinetic, ubuntu~jammy, debian~testing, debian~bullseye, arch~rolling]
        os: [fedora~37]
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: setup-build-deps
        uses: ./.github/actions/deps

      - name: setup-mkosi
        uses: systemd/mkosi@80b496787c016b46c7d68a8a23a6d3f2a5605abb

      - name: split-os
        id: split-os
        shell: bash
        env:
          MATRIX_OS: ${{ matrix.os }}
        run: |
          IFS='~' read -ra OS <<< "${MATRIX_OS}"
          echo "distribution=${OS[0]}" >> "$GITHUB_OUTPUT"
          echo "release=${OS[1]}" >> "$GITHUB_OUTPUT"

      - name: Build image
        env:
          ARCH: ${{ matrix.arch }}
          DISTRIBUTION: ${{ steps.split-os.outputs.distribution }}
          RELEASE: ${{ steps.split-os.outputs.release }}
        run: |
          sudo mkosi --architecture "${ARCH}" --distribution "${DISTRIBUTION}" --release "${RELEASE}" --format=tar --compress-output=xz

      # - name: Upload raspbian
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: raspbian
      #     path: raspbian/image.zip
